### ISSUE TITLE
Safari and Firefox support

### ISSUE THREAD

**Issue by heyngra** [heyngra/TCain-Explorer-Web#4]
# This site does NOT work with Firefox and Safari.
The issue is in [PointerEvent](https://github.com/heyngra/TCain-Explorer-Web/blob/main/static/app.js#L105) which is not available at least in my version of Firefox (106.0.1)
```
Uncaught TypeError: event.path is undefined
    getRecipes https://tcain.heyn.live/static/app.js:105
6 app.js:105:5
```

**Comment by SpeedeKowskyy** [comment]
skill issue
